name: pre-release

on:
  push:
    branches:
      - "main"

jobs:
  tagged-release:
    name: Pre Release
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: make all
      
      - name: Test
        run: make test

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Development Build"
          files: |
            *.tar.gz
            *.zip
