name: "tag-latest"

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - "main"

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  release:
    name: "Tag Latest"
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
